version: '3'
services:
  adminer:
    image: "adminer"
    ports:
      - "88:8080"
    depends_on:
      - "db"
    networks: 
      - dev-network
  db:
    image: "mysql:5.6"
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/db_init.sql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "3306:3306"
    networks: 
      - dev-network

networks:
  dev-network: 